server:
  port: 9004
spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.170:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb+srv://root:783328905@cluster0-fdtvl.mongodb.net/ct_mongodb
  redis:
    host: 101.132.126.62
    port: 6379
    password: 783328905
    pool:
     max-idle: 100
     min-idle: 1
     max-active: 1000
     max-wait: -1
    database: 1
  rabbitmq:
    host: 192.168.25.170
mybatis-plus:
 typeAliasesPackage: com.tensquare.article.pojo
 global-config:
   db-config:
    id-type: input
 configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
