server:
  port: 9008
spring:
 application:
     name: tensquare-user
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://192.168.25.170:3306/tensquare_user?characterEncoding=utf-8
   username: root
   password: root
mybatis-plus:
 typeAliasesPackage: com.tensquare.user.pojo
 global-config:
   db-config:
    id-type: input
 configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
